SELECT 
    YEAR(OS.SALES_DATE) AS YEAR, 
    MONTH(OS.SALES_DATE) AS MONTH, 
    COUNT(DISTINCT UI.USER_ID) AS PUCHASED_USERS, 
    ROUND(COUNT(DISTINCT UI.USER_ID) / (
    SELECT COUNT(*) 
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'), 1) AS PUCHASED_RATIO
FROM (
    SELECT * 
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021') AS UI
JOIN ONLINE_SALE OS
ON UI.USER_ID = OS.USER_ID
GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE)
ORDER BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE)
