SELECT i.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, avg_score as SCORE
FROM REST_INFO i 
JOIN
    (SELECT REST_ID, round(AVG(REVIEW_SCORE),2) avg_score
    FROM REST_REVIEW
    GROUP BY REST_ID) a
ON i.REST_ID = a.REST_ID
WHERE ADDRESS like '서울%'
ORDER BY SCORE DESC, FAVORITES DESC