SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O
LEFT OUTER JOIN ANIMAL_INS I
ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL
ORDER BY O.ANIMAL_ID

# SELECT O.ANIMAL_ID, O.NAME
# FROM ANIMAL_OUTS O
# WHERE O.ANIMAL_ID NOT IN (
#     SELECT ANIMAL_ID
#     FROM ANIMAL_INS
# )
# ORDER BY ANIMAL_ID