SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD A
JOIN USED_GOODS_USER B ON B.USER_ID = A.WRITER_ID
GROUP BY B.USER_ID, B.NICKNAME, A.STATUS
HAVING SUM(A.PRICE) >= 700000 and A.STATUS = 'DONE'
ORDER BY TOTAL_SALES ASC;
